name: Build and Release

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build executable
        run: |
          python -m PyInstaller StammGUI.spec

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: StammGui-Windows
          path: dist/StammGui.exe
          retention-days: 30

      - name: Create Release (on tag push)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: dist/StammGui.exe
          body: |
            🚀 **Tribal Wars Support Tab Bot - Release ${{ github.ref_name }}**

            ## 📦 Download
            - Windows: `StammGui.exe`

            ## 🎯 Features
            - SOS-Anfragen parsen
            - Optimale Tab-Berechnung
            - Export für DS Ultimate

            ## 🔧 Installation
            1. Download `StammGui.exe`
            2. Ausführen - keine weitere Installation nötig!

            ## 📋 Changelog
            - See commit history for detailed changes

          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
