name: Build and Release

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify files exist
        run: |
          echo "Checking for required files..."
          if (Test-Path "StammGui.py") { echo "✅ StammGui.py found" } else { echo "❌ StammGui.py missing"; exit 1 }
          if (Test-Path "StammGUI.spec") { echo "✅ StammGUI.spec found" } else { echo "❌ StammGUI.spec missing"; exit 1 }
          if (Test-Path "support.ico") { echo "✅ support.ico found" } else { echo "❌ support.ico missing"; exit 1 }
          if (Test-Path "images") { echo "✅ images folder found" } else { echo "❌ images folder missing"; exit 1 }

      - name: Build executable with PyInstaller
        run: |
          echo "Building executable..."
          python -m PyInstaller StammGUI.spec --clean

      - name: Verify build output
        run: |
          if (Test-Path "dist/StammGui.exe") { 
            echo "✅ Build successful - StammGui.exe created"
            $fileSize = (Get-Item "dist/StammGui.exe").Length / 1MB
            echo "📦 File size: $([math]::Round($fileSize, 2)) MB"
          } else { 
            echo "❌ Build failed - StammGui.exe not found"
            exit 1 
          }

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/StammGui.exe
          body: |
            🚀 **Tribal Wars Support Tab Bot - Release ${{ github.ref_name }}**

            ## 📦 Download
            - **Windows**: `StammGui.exe` (keine Installation erforderlich)

            ## 🎯 Features
            - SOS-Anfragen parsen und analysieren
            - Optimale Tab-Berechnung für Unterstützung
            - Export für DS Ultimate Browser-Erweiterung
            - Automatisches Laden der Weltgeschwindigkeiten

            ## 🔧 Installation
            1. Download `StammGui.exe`
            2. Ausführen - keine weitere Installation nötig!
            3. Welt-ID eingeben und loslegen

            ## 📋 Changelog
            Siehe [Commit-History](https://github.com/MarcoMue/Tribal-Wars-Support-Tab-Bot/commits/${{ github.ref_name }}) für detaillierte Änderungen.

          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload build logs (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs-${{ github.sha }}
          path: |
            build/
            *.log
          if-no-files-found: ignore
